#!/bin/bash

# config
MAX_TEMP=40
# set column width
COLUMNS=2
# colors
white="\e[39m"
green="\e[1;32m"
red="\e[1;31m"
dim="\e[2m"
undim="\e[0m"

# disks to check
num_disks=$(lsblk -J | jq '.blockdevices | length')

out=""
for ((i = 0; i < num_disks; i++)) ; do
    disk=$(lsblk -J | jq -r ".blockdevices.[$i].name")

    if [[ "$disk" = "sd"* ]]; then
        disk_status=$(smartctl --all "/dev/${disk}" --json)

        uuid=$(blkid -s UUID -o value "/dev/${disk}")
        smart_status=$(echo $disk_status | jq '.smart_status.passed')
        temp=$(echo $disk_status | jq -r '.ata_smart_attributes.table | map(select(.name=="Temperature_Celsius")) | .[0].raw.string' | cut -d " " -f 1)

        # color green if temp <= MAX_TEMP, else red
        if [[ "${temp}" -gt "${MAX_TEMP}" ]]; then
            color=$red
        else
            color=$green
        fi
        # add "C" if temp is numeric
        if [[ "$temp" =~ ^[0-9]+$ ]]; then
            temp="${temp}C"
        fi
        # color green if status is "without error", else red
        if [[ "${smart_status}" == "true" ]]; then
            status="Healthy"
            status_color=$green
        else
            status_color=$red
            status="Failed"
        fi

        # print temp & smartd error
        out+="${disk}:,${color}${temp}${undim} | ${status_color}${status}${undim},"
        # insert \n every $COLUMNS column
        if [ $((($i+1) % $COLUMNS)) -eq 0 ]; then
            out+="\n"
        fi
    fi
done
out+="\n"

printf "\ndisk status:\n"
printf "$out" | column -ts $',' | sed -e 's/^/  /'
echo 